export const data = [
  {
    question: "Which device is required for internet connection?",
    option1: "Modem",
    option2: "Router",
    option3: "LAN Cable",
    option4: "Pen Drive",
    ans: 1,
  },
  {
    question: "What does CPU stand for?",
    option1: "Central Processing Unit",
    option2: "Computer Personal Unit",
    option3: "Central Process Unit",
    option4: "Central Processor Unit",
    ans: 1,
  },
  {
    question:
      "Which programming language is known as the 'mother of all languages'?",
    option1: "C",
    option2: "Java",
    option3: "Fortran",
    option4: "Assembly",
    ans: 3,
  },
  {
    question: "What does HTML stand for?",
    option1: "Hyper Text Markup Language",
    option2: "High Tech Markup Language",
    option3: "Hyperlink and Text Markup Language",
    option4: "Home Tool Markup Language",
    ans: 1,
  },
  {
    question: "What is the capital of France?",
    option1: "Berlin",
    option2: "Madrid",
    option3: "Paris",
    option4: "Rome",
    ans: 3,
  },
  {
    question: "Which planet is known as the 'Red Planet'?",
    option1: "Mars",
    option2: "Jupiter",
    option3: "Venus",
    option4: "Mercury",
    ans: 1,
  },
  {
    question: "What is the largest mammal in the world?",
    option1: "Elephant",
    option2: "Blue Whale",
    option3: "Giraffe",
    option4: "Hippopotamus",
    ans: 2,
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    option1: "Charles Dickens",
    option2: "Jane Austen",
    option3: "William Shakespeare",
    option4: "Mark Twain",
    ans: 3,
  },
  {
    question: "What is the currency of Japan?",
    option1: "Yuan",
    option2: "Won",
    option3: "Yen",
    option4: "Ringgit",
    ans: 3,
  },
  {
    question: "Which element has the chemical symbol 'O'?",
    option1: "Oxygen",
    option2: "Gold",
    option3: "Silver",
    option4: "Iron",
    ans: 1,
  },
];
